# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findudC <- function(v) {
    .Call(`_Rsenal_findudC`, v)
}

ioaC <- function(x, y) {
    .Call(`_Rsenal_ioaC`, x, y)
}

