# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findudC <- function(v) {
    .Call('Rsenal_findudC', PACKAGE = 'Rsenal', v)
}

ioaC <- function(x, y) {
    .Call('Rsenal_ioaC', PACKAGE = 'Rsenal', x, y)
}

